version: 0.2
env:
  variables:
    ECR_REPOSITORY: 241706223331.dkr.ecr.ap-northeast-1.amazonaws.com/sprint6-ecr
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${ECR_REPOSITORY}
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t sprint6-container .
      - docker tag sprint6-container:latest ${ECR_REPOSITORY}:${IMAGE_TAG}
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ${ECR_REPOSITORY}:${IMAGE_TAG}
      - echo Build completed on `date`
      - echo Creating imagedefinitions.json...
      - |
        echo '[
          {
            "name": "sprint6-container",
            "imageUri": "'${ECR_REPOSITORY}':'${IMAGE_TAG}'"
          }
        ]' > imagedefinitions.json
      - echo imagedefinitions.json created.
artifacts:
  files:
    - imagedefinitions.json
